//! Themes index — beginner-facing taxonomy + per-book assignments.
//!
//! The themes.json file is generated by `fathom-build classify-themes` and
//! baked into the binary via `include_bytes!`. The runtime calls into this
//! module to populate the left-rail UI and the per-theme book lists.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::sync::OnceLock;

const THEMES_JSON: &[u8] = include_bytes!("../data/themes.json");

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThemeEntry {
    pub slug: String,
    pub label: String,
    pub order: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThemeAssignment {
    pub gutenberg_id: u32,
    pub themes: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DroppedBook {
    pub gutenberg_id: u32,
    pub reason: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThemesMetadata {
    pub books_classified: usize,
    pub books_in_other: usize,
    pub books_dropped: usize,
    pub model: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThemesFile {
    pub version: u32,
    pub generated_at: String,
    pub themes: Vec<ThemeEntry>,
    pub assignments: Vec<ThemeAssignment>,
    pub dropped: Vec<DroppedBook>,
    pub metadata: ThemesMetadata,
}

/// Cached parsed themes.json (parsed once per process).
fn themes_file() -> &'static ThemesFile {
    static CELL: OnceLock<ThemesFile> = OnceLock::new();
    CELL.get_or_init(|| {
        serde_json::from_slice(THEMES_JSON).expect("themes.json shipped in-binary must parse")
    })
}

/// All themes in declared order.
pub fn all_themes() -> &'static [ThemeEntry] {
    &themes_file().themes
}

/// Per-theme book counts. Initialised at 0 for every declared theme, then
/// incremented per assignment. Callers may filter on `count > 0` if they
/// want the non-empty subset.
pub fn theme_counts() -> BTreeMap<String, usize> {
    let mut counts: BTreeMap<String, usize> = BTreeMap::new();
    for theme in &themes_file().themes {
        counts.insert(theme.slug.clone(), 0);
    }
    for a in &themes_file().assignments {
        for slug in &a.themes {
            *counts.entry(slug.clone()).or_insert(0) += 1;
        }
    }
    counts
}

/// Gutenberg IDs tagged with this theme, in declared assignment order.
pub fn books_in_theme(slug: &str) -> Vec<u32> {
    themes_file()
        .assignments
        .iter()
        .filter(|a| a.themes.iter().any(|s| s == slug))
        .map(|a| a.gutenberg_id)
        .collect()
}

/// Set of gutenberg_ids that were curated out of the user-visible library
/// (duplicates / history-of-philosophy / biography / intro-textbook).
pub fn dropped_ids() -> std::collections::HashSet<u32> {
    themes_file().dropped.iter().map(|d| d.gutenberg_id).collect()
}

pub fn parse_themes_bytes(bytes: &[u8]) -> Result<ThemesFile> {
    serde_json::from_slice(bytes).context("parse themes.json")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn baked_themes_json_parses() {
        let f = themes_file();
        assert_eq!(f.version, 1);
        assert!(!f.themes.is_empty(), "must ship at least seed taxonomy");
    }

    #[test]
    fn other_is_pinned_to_order_99() {
        let other = all_themes().iter().find(|t| t.slug == "other").unwrap();
        assert_eq!(other.order, 99);
    }

    #[test]
    fn parse_themes_bytes_round_trip() {
        let bytes = include_bytes!("../data/themes.json");
        let parsed = parse_themes_bytes(bytes).unwrap();
        assert_eq!(parsed.version, 1);
    }

    #[test]
    fn theme_counts_returns_entry_for_every_declared_theme() {
        let counts = theme_counts();
        for theme in all_themes() {
            assert!(counts.contains_key(&theme.slug), "missing {}", theme.slug);
        }
    }

    #[test]
    fn dropped_ids_matches_dropped_list() {
        // Whatever themes.json ships, dropped_ids() must return exactly
        // the gutenberg_ids present in the dropped list — no more, no less.
        let f = themes_file();
        let expected: std::collections::HashSet<u32> =
            f.dropped.iter().map(|d| d.gutenberg_id).collect();
        assert_eq!(dropped_ids(), expected);
        assert_eq!(dropped_ids().len(), f.metadata.books_dropped);
    }
}
